# Generated by Django 3.2.6 on 2021-09-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
                'db_table': 'Basket',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('exhname', models.CharField(blank=True, default='알 수 없는 전시회', max_length=64, primary_key=True, serialize=False, verbose_name='전시회명')),
                ('exhperiod', models.CharField(max_length=17, verbose_name='전시 기간')),
                ('exhstat', models.CharField(choices=[('P', '지난 전시'), ('C', '현재 전시'), ('U', '전시 예정')], max_length=1, verbose_name='전시 상태')),
                ('exhreview', models.TextField(default='리뷰 없음', max_length=200, verbose_name='전시리뷰')),
                ('exhimage', models.ImageField(blank=True, upload_to='', verbose_name='전시포스터')),
            ],
            options={
                'verbose_name': '전시회',
                'verbose_name_plural': '전시회',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(blank=True, default='알 수 없는 사용자', max_length=20, primary_key=True, serialize=False, verbose_name='아이디')),
                ('userpw', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('userphone', models.CharField(max_length=11, verbose_name='휴대폰')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
                ('username', models.ManyToManyField(max_length=20, through='bora.Basket', to='bora.Product', verbose_name='사용자명')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='what',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bora.product', verbose_name='예매 내역'),
        ),
        migrations.AddField(
            model_name='basket',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bora.user', verbose_name='예매자'),
        ),
    ]
