# Generated by Django 3.2.6 on 2021-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basketuser',
            field=models.ManyToManyField(max_length=20, through='bora.Basket', to='bora.Product', verbose_name='장바구니 사용자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False, verbose_name='아이디'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='사용자명'),
        ),
    ]
