# Generated by Django 3.2.6 on 2021-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0002_auto_20210906_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exhname',
            field=models.CharField(blank=True, default='', max_length=64, primary_key=True, serialize=False, verbose_name='전시회명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exhreview',
            field=models.TextField(max_length=200, null=True, verbose_name='전시리뷰'),
        ),
    ]
