# Generated by Django 3.2.6 on 2021-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0004_auto_20210909_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exhinfo',
            field=models.TextField(default='', max_length=200, verbose_name='전시 정보'),
        ),
        migrations.AlterField(
            model_name='user',
            name='basketuser',
            field=models.ManyToManyField(max_length=20, related_name='basketuser', through='bora.Basket', to='bora.Product', verbose_name='장바구니 사용자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='사용자명'),
        ),
    ]
