# Generated by Django 3.2.6 on 2021-09-17 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0005_auto_20210915_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.SmallIntegerField(default=1, verbose_name='인원'),
        ),
        migrations.AddField(
            model_name='product',
            name='exhcalender',
            field=models.DateField(default=datetime.date.today, verbose_name='전시 기간 달력'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='what',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bora.product', verbose_name='예매 전시'),
        ),
    ]
