# Generated by Django 3.2.6 on 2021-09-18 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0006_auto_20210917_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exhcalender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exhperiod',
        ),
        migrations.AddField(
            model_name='product',
            name='exhend',
            field=models.DateField(default=datetime.date.today, verbose_name='전시 종료'),
        ),
        migrations.AddField(
            model_name='product',
            name='exhstart',
            field=models.DateField(default=datetime.date.today, verbose_name='전시 시작'),
        ),
    ]
