# Generated by Django 3.2.6 on 2021-09-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0007_auto_20210918_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exhstat',
        ),
    ]
