# Generated by Django 3.2.6 on 2021-09-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0008_remove_product_exhstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exhinfo',
            field=models.TextField(default='', max_length=250, verbose_name='전시 정보'),
        ),
    ]
