# Generated by Django 3.2.6 on 2021-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0009_alter_product_exhinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='writetime',
            field=models.DateTimeField(auto_now=True, verbose_name='리뷰 작성 시간'),
        ),
    ]
