# Generated by Django 3.2.6 on 2021-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0010_review_writetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exhimage',
            field=models.ImageField(blank=True, upload_to='bora/productimage', verbose_name='전시포스터'),
        ),
    ]
