# Generated by Django 3.2.6 on 2021-10-05 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0011_alter_product_exhimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='when',
            field=models.DateTimeField(auto_now=True, verbose_name='예매 시간'),
        ),
        migrations.AddField(
            model_name='product',
            name='exhurl',
            field=models.URLField(default=1, verbose_name='웹사이트'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='인원'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exhimage',
            field=models.ImageField(blank=True, upload_to='member/productimage', verbose_name='전시포스터'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userphone',
            field=models.CharField(default='', max_length=11, verbose_name='휴대폰'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpw',
            field=models.CharField(default='', max_length=20, verbose_name='비밀번호'),
        ),
    ]
