# Generated by Django 3.2.6 on 2021-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0012_auto_20211005_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exhimage',
            field=models.ImageField(blank=True, upload_to='bora', verbose_name='전시포스터'),
        ),
    ]
